//%attributes = {}
  //libusb: SONY S380 specific (doesn't work for other models!)

$options:=New object:C1471("libusb";True:C214)
$readers:=SCARD Get readers ($options)

$readers:=$readers.query("usb != null")

If ($readers.length#0)
	
	$reader:=$readers[0]
	
	$reader.timeout:=9  //seconds
	$reader.card:="TypeA"
	
	$status:=SCARD Read tag ($reader)
	
	If ($status.success)
		
		  //pupi=Pseudo-Unique Identifier
		  //used to differenciate PICCs during anticollision. 
		  //This 4-byte number may be either a number dinamically generated by the PICC 
		  //or a diversified fixed number
		  //appdata=application data
		  //pinfo=protocol data
		
		ALERT:C41($status.pupi+":"+$status.appdata+":"+$status.pinfo)
	End if 
	
End if 